server:
  port: ${PORT:8080}
  servlet:
    context-path: /rehearsal-base

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${SERVICE_DISCOVERY_HOST:localhost}:${SERVICE_DISCOVERY_PORT:8761}/eureka

zuul:
  prefix: "/api"
  strip-prefix: true
  routes:
    rooms:
      path: /rooms/**
      url: http://${REHEARSAL_SERVICE_HOST:localhost}:${REHEARSAL_SERVICE_PORT:8888}/rehearsal-service/rooms
    room:
      path: /room/**
      url: http://${REHEARSAL_SERVICE_HOST:localhost}:${REHEARSAL_SERVICE_PORT:8888}/rehearsal-service/room
    sms:
      path: /sms/**
      strip-prefix: true
      url: http://${SMS_SERVICE_HOST:localhost}:${SMS_SERVICE_PORT:8085}/sms-service

feign:
  client:
    config:
      default:
        connectTimeout: 15000
        readTimeout: 15000
        loggerLevel: full
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: metrics, health
  endpoint:
    health:
      show-details: always

app:
  oauth2:
    client-id: ${CLIENT_ID:any_id}
    client-secret: ${CLIENT_SECRET:any_secret}
    signing-key: ${SIGN_KEY:987654321}
  rehearsal-base:
    info:
      name: ${NAME:"Невеселые ребята"}
      address: ${ADDRESS:Не дом и не улица, 13/666}
      phone: ${PHONE:+7(123)500-05-05}
    timetable:
      startHour: ${START_HOUR:9}
      endHour: ${END_HOUR:24}
      periodInDays: ${TIMETABLE_PERIOD:7}

logging:
  level:
    org:
      springframework:
        security: ${LOG_LEVEL:DEBUG}