server:
  port: ${PORT:8085}
  servlet:
    context-path: /sms-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${SERVICE_DISCOVERY_HOST:localhost}:${SERVICE_DISCOVERY_PORT:8761}/eureka

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/sms_code_base
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:testpassword}
    driverClassName: org.postgresql.Driver
    initialization-mode: always
  jpa:
    show-sql: ${SHOW_SQL:true}
  zipkin:
    baseUrl: http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}

management:
  endpoints:
    web:
      exposure:
        include: metrics, health
  endpoint:
    health:
      show-details: always

sms-code:
  expirationTimeInSeconds: ${SMS_CODE_EXPIRATION_TIME_IN_SECONDS:90}
  waitingInterval: ${WAITING_INTERVAL_IN_SECONDS:60} #seconds
  countRequestsInterval: ${COUNT_REQUESTS_INTERVAL:300} #seconds
  requestsNumber: ${REQUESTS_NUMBER:3}

logging:
  level:
    org:
      springframework:
        security: ${LOG_LEVEL:DEBUG}


