server:
  port: ${AUTHORIZATION_SERVER_PORT:8090}
  servlet:
    context-path: /auth-server

eureka:
  client:
    fetch-registry: true

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://${AUTHORIZATION_SERVER_DB_HOST:localhost}:${AUTHORIZATION_SERVER_DB_PORT:5432}/rehearsal_base_user
    username: postgres
    password: testpassword
    driverClassName: org.postgresql.Driver
    initialization-mode: always
  jpa:
    show-sql: true

app:
  oauth2:
    client-id: "any_id"
    client-secret: "any_secret"
    signing-key: 987654321

logging:
  level:
    org:
      springframework:
        security: ${AUTHORIZATION_SERVER_LOG_LEVEL:DEBUG}

