server:
  port: ${PORT:8090}
  servlet:
    context-path: /auth-server

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${SERVICE_DISCOVERY_HOST:localhost}:${SERVICE_DISCOVERY_PORT:8761}/eureka

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/rehearsal_base_user
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:testpassword}
    driverClassName: org.postgresql.Driver
    initialization-mode: always
  jpa:
    show-sql: ${SHOW_SQL:true}

app:
  oauth2:
    client-id: ${CLIENT_ID:any_id}
    client-secret: ${CLIENT_SECRET:any_secret}
    signing-key: ${SIGN_KEY:987654321}

logging:
  level:
    org:
      springframework:
        security: ${LOG_LEVEL:DEBUG}

